[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "docker-r-env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.2,<4.6"
r-ggplot2 = ">=4.0.1,<5"
"r-data.table" = ">=1.17.8,<2"
r-stringr = ">=1.6.0,<2"
r-reactable = ">=0.4.4,<0.5"
bioconductor-complexheatmap = ">=1.6.0,<2"
r-plotly = ">=4.11.0,<5"
r-heatmaply = ">=1.6.0,<2"
jupyterlab = ">=4.5.0,<5"
r-irkernel = ">=1.3.2,<2"
